# Generated by Django 4.1.3 on 2022-11-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='application',
            name='declined',
        ),
        migrations.RemoveField(
            model_name='application',
            name='pending',
        ),
    ]
