# Generated by Django 4.1.3 on 2022-11-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_application_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=True)),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
        ),
    ]
