# Generated by Django 4.1.3 on 2022-11-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='is_booked',
            new_name='is_available',
        ),
    ]
